name: bible_app
description: The Bible that listens and speaks your language.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.0   # for bookmarks
  flutter_tts: ^4.0.2           # for Bible Listen

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/bibles/web/
    - assets/bibles/bsb/
    - assets/bibles/pidgin/
    - assets/bibles/yoruba/