import 'dart:convert';
import 'package:flutter/foundation.dart';
import 'package:google_generative_ai/google_generative_ai.dart';

/// A quiz question generated by AI.
class AiQuizQuestion {
  final String question;
  final String correctAnswer;
  final List<String> options;
  final String explanation;
  final String verseRef;

  const AiQuizQuestion({
    required this.question,
    required this.correctAnswer,
    required this.options,
    required this.explanation,
    required this.verseRef,
  });

  factory AiQuizQuestion.fromJson(Map<String, dynamic> json) {
    final options = (json['options'] as List<dynamic>?)
            ?.map((e) => e.toString())
            .toList() ??
        [];
    return AiQuizQuestion(
      question: json['question']?.toString() ?? '',
      correctAnswer: json['correctAnswer']?.toString() ?? '',
      options: options,
      explanation: json['explanation']?.toString() ?? '',
      verseRef: json['verseRef']?.toString() ?? '',
    );
  }
}

/// Wraps Gemini Flash for Bible-focused AI features.
///
/// Operates in a stateless fashion: call [init] with an API key,
/// then use the static methods. Falls back gracefully when offline.
class AiService {
  static const _systemInstruction = '''
You are a knowledgeable biblical scholar and teacher. You provide accurate,
well-researched biblical insights that are accessible to everyday readers.

Guidelines:
- Be scholarly but approachable — avoid overly academic jargon.
- Welcome all Christian denominations and traditions respectfully.
- When discussing interpretation, note where traditions may differ.
- Provide historical and cultural context where helpful.
- Always ground your answers in Scripture.
- Be concise and direct — users are reading on a mobile device.
- When returning JSON, return ONLY valid JSON with no markdown fences.
''';

  static GenerativeModel? _model;

  /// Initialize with a Gemini API key. Call once (e.g. at app start).
  static void init(String apiKey) {
    if (apiKey.trim().isEmpty) {
      _model = null;
      return;
    }
    _model = GenerativeModel(
      model: 'gemini-2.0-flash',
      apiKey: apiKey.trim(),
      systemInstruction: Content.text(_systemInstruction),
      generationConfig: GenerationConfig(
        temperature: 0.7,
        maxOutputTokens: 4096,
      ),
    );
  }

  /// Whether the AI service has been initialized with a valid key.
  static bool get isAvailable => _model != null;

  /// Test the connection by sending a minimal prompt.
  static Future<bool> testConnection() async {
    if (!isAvailable) return false;
    try {
      final response = await _model!.generateContent([
        Content.text('Respond with exactly: OK'),
      ]);
      return response.text?.trim().isNotEmpty ?? false;
    } catch (e) {
      debugPrint('AI connection test failed: $e');
      return false;
    }
  }

  // ─── Similar Verses ─────────────────────────────────────────

  /// Returns semantically similar verses with AI-generated explanations.
  static Future<List<({String reference, String text, String reason})>>
      findSimilarVerses(String verseText, String verseRef) async {
    if (!isAvailable) return [];

    final prompt = '''
Find 10-15 Bible verses that are thematically or theologically similar to this verse:

Reference: $verseRef
Text: "$verseText"

Return a JSON array of objects. Each object must have:
- "reference": the verse reference (e.g. "Romans 8:28")
- "text": the full verse text (use a standard English translation)
- "reason": a brief (1-2 sentence) explanation of why this verse is similar

Return ONLY the JSON array, no other text.
''';

    try {
      final response = await _model!.generateContent([Content.text(prompt)]);
      final raw = _extractJson(response.text ?? '');
      final List<dynamic> items = json.decode(raw) as List<dynamic>;
      return items.map((item) {
        final map = item as Map<String, dynamic>;
        return (
          reference: map['reference']?.toString() ?? '',
          text: map['text']?.toString() ?? '',
          reason: map['reason']?.toString() ?? '',
        );
      }).toList();
    } catch (e) {
      debugPrint('AI findSimilarVerses error: $e');
      return [];
    }
  }

  // ─── Quiz Generation ────────────────────────────────────────

  /// Generates 5-6 varied quiz questions for a chapter.
  static Future<List<AiQuizQuestion>> generateQuiz(
    String book,
    int chapter,
    List<String> verseTexts,
  ) async {
    if (!isAvailable) return [];

    // Send a subset of verses to keep prompt size manageable
    final sampleVerses = verseTexts.length > 20
        ? (verseTexts.toList()..shuffle()).take(20).toList()
        : verseTexts;

    final versesBlock =
        sampleVerses.asMap().entries.map((e) => 'Verse ${e.key + 1}: ${e.value}').join('\n');

    final prompt = '''
Generate 6 quiz questions about $book chapter $chapter based on these verses:

$versesBlock

Use a VARIETY of question types. Choose from these types:
1. Complete the verse (fill in missing words)
2. Which verse says this (identify the verse number)
3. True or False
4. Fill in the blank (single key word)
5. Who said/did this?
6. What happened next/before?
7. What is the main theme/lesson?
8. Match the person to their action
9. Where did this take place?
10. Why did this happen?
11. What does this word/phrase mean in context?
12. Compare and contrast (which statement is correct?)

Each question MUST use a different type from the list above.

Return a JSON array of 6 objects. Each object must have:
- "question": the question text
- "correctAnswer": the correct answer
- "options": array of 4 answer choices (including the correct one, shuffled)
- "explanation": a brief explanation of why the answer is correct (1-2 sentences, include relevant verse reference)
- "verseRef": the verse number(s) this question is based on (e.g. "3" or "5-7")

Return ONLY the JSON array, no other text.
''';

    try {
      final response = await _model!.generateContent([Content.text(prompt)]);
      final raw = _extractJson(response.text ?? '');
      final List<dynamic> items = json.decode(raw) as List<dynamic>;
      return items
          .map((item) => AiQuizQuestion.fromJson(item as Map<String, dynamic>))
          .where((q) =>
              q.question.isNotEmpty &&
              q.correctAnswer.isNotEmpty &&
              q.options.length >= 2)
          .toList();
    } catch (e) {
      debugPrint('AI generateQuiz error: $e');
      return [];
    }
  }

  // ─── Verse Explanation ──────────────────────────────────────

  /// Returns a clear, accessible explanation of a verse.
  static Future<String> explainVerse(
      String verseRef, String verseText) async {
    if (!isAvailable) return '';

    final prompt = '''
Explain this Bible verse in a clear, accessible way:

$verseRef: "$verseText"

Include:
1. What this verse means in plain language
2. Brief historical/cultural context
3. How it connects to the broader chapter/book
4. A practical takeaway for today

Keep the total explanation under 200 words.
''';

    try {
      final response = await _model!.generateContent([Content.text(prompt)]);
      return response.text?.trim() ?? '';
    } catch (e) {
      debugPrint('AI explainVerse error: $e');
      return '';
    }
  }

  // ─── Ask the Bible ──────────────────────────────────────────

  /// Answers a free-form question about the Bible.
  static Future<String> askBible(String question) async {
    if (!isAvailable) return '';

    final prompt = '''
Answer this Bible question:

"$question"

Provide a thorough but concise answer (under 300 words).
Reference specific Bible verses to support your answer.
If the question is unclear or not about the Bible, politely redirect.
''';

    try {
      final response = await _model!.generateContent([Content.text(prompt)]);
      return response.text?.trim() ?? '';
    } catch (e) {
      debugPrint('AI askBible error: $e');
      return '';
    }
  }

  // ─── Smart Search ───────────────────────────────────────────

  /// Given a natural-language query (paraphrase, topic, or fragment),
  /// asks Gemini to return the best-matching canonical verse references.
  ///
  /// Returns a list of (reference, text, reason) where `reference` is in the
  /// format "Book Chapter:Verse" (e.g. "Hebrews 12:29") — callers can then
  /// resolve these against local translations.
  static Future<({String overview, List<({String reference, String text, String reason})> hits})>
      searchWithAI(String query) async {
    if (!isAvailable) {
      return (overview: '', hits: <({String reference, String text, String reason})>[]);
    }

    final prompt = '''
A user searched the Bible for: "$query"

Task: Identify the 5-10 Bible verses that best match this query — whether it's
a paraphrase, a theme, a topic, or a fragment. Consider multiple translations
(KJV, NIV, ESV, NLT, WEB) when matching paraphrases.

Return a JSON object with two fields:
1. "overview": a 2-3 sentence plain-English interpretation of what the query means
   biblically (like a Google AI Overview). Mention the primary verses by reference.
2. "hits": an array of matching verses. Each entry must have:
   - "reference": exact canonical reference, format "Book Chapter:Verse" (e.g. "Hebrews 12:29", "Deuteronomy 4:24")
   - "text": the full verse text in a standard English translation
   - "reason": a brief (under 20 words) explanation of how this verse matches the query

Rank hits by relevance. Place exact matches first, then paraphrases, then related themes.

Return ONLY valid JSON, no markdown fences, no commentary before or after.
''';

    try {
      final response = await _model!.generateContent([Content.text(prompt)]);
      final raw = _extractJson(response.text ?? '');
      final decoded = json.decode(raw);
      if (decoded is! Map<String, dynamic>) {
        return (overview: '', hits: <({String reference, String text, String reason})>[]);
      }
      final overview = decoded['overview']?.toString() ?? '';
      final hitsList = decoded['hits'] as List<dynamic>? ?? const [];
      final hits = hitsList.map((item) {
        final map = item as Map<String, dynamic>;
        return (
          reference: map['reference']?.toString() ?? '',
          text: map['text']?.toString() ?? '',
          reason: map['reason']?.toString() ?? '',
        );
      }).where((h) => h.reference.isNotEmpty).toList();
      return (overview: overview, hits: hits);
    } catch (e) {
      debugPrint('AI searchWithAI error: $e');
      return (overview: '', hits: <({String reference, String text, String reason})>[]);
    }
  }

  // ─── Helpers ────────────────────────────────────────────────

  /// Extracts JSON from a response that may contain markdown fences.
  static String _extractJson(String raw) {
    var cleaned = raw.trim();
    // Strip markdown code fences
    if (cleaned.startsWith('```')) {
      final firstNewline = cleaned.indexOf('\n');
      if (firstNewline != -1) {
        cleaned = cleaned.substring(firstNewline + 1);
      }
      if (cleaned.endsWith('```')) {
        cleaned = cleaned.substring(0, cleaned.length - 3);
      }
    }
    cleaned = cleaned.trim();
    // Find the first [ or { and last ] or }
    final startBracket = cleaned.indexOf('[');
    final startBrace = cleaned.indexOf('{');
    int start;
    if (startBracket == -1) {
      start = startBrace;
    } else if (startBrace == -1) {
      start = startBracket;
    } else {
      start = startBracket < startBrace ? startBracket : startBrace;
    }
    if (start == -1) return cleaned;

    final isArray = cleaned[start] == '[';
    final end = isArray
        ? cleaned.lastIndexOf(']')
        : cleaned.lastIndexOf('}');
    if (end == -1 || end <= start) return cleaned;
    return cleaned.substring(start, end + 1);
  }
}
