import 'kids_stories.dart';

/// Additional New Testament stories for kids.
const kKidsStoriesNT = <KidsStory>[
  KidsStory(
    title: 'Jesus is Baptized',
    emoji: '🕊️',
    book: 'Matthew', chapter: 3, startVerse: 13, endVerse: 17,
    blurb: 'A dove comes down and God speaks from heaven.',
    color: 0xFF0288D1,
  ),
  KidsStory(
    title: 'Jesus Feeds 5000',
    emoji: '🍞',
    book: 'John', chapter: 6, startVerse: 1, endVerse: 14,
    blurb: 'Five loaves and two fish feed thousands.',
    color: 0xFF689F38,
  ),
  KidsStory(
    title: 'The Good Samaritan',
    emoji: '🤝',
    book: 'Luke', chapter: 10, startVerse: 25, endVerse: 37,
    blurb: 'A stranger helps when nobody else would.',
    color: 0xFFE65100,
  ),
  KidsStory(
    title: 'Zacchaeus',
    emoji: '🌳',
    book: 'Luke', chapter: 19, startVerse: 1, endVerse: 10,
    blurb: 'A little man climbs a big tree to see Jesus.',
    color: 0xFF2E7D32,
  ),
  KidsStory(
    title: 'Jesus Walks on Water',
    emoji: '🌊',
    book: 'Matthew', chapter: 14, startVerse: 22, endVerse: 33,
    blurb: 'Peter steps out of the boat onto the sea.',
    color: 0xFF1976D2,
  ),
  KidsStory(
    title: 'The Prodigal Son',
    emoji: '🏠',
    book: 'Luke', chapter: 15, startVerse: 11, endVerse: 32,
    blurb: 'A son comes home and his father runs to hug him.',
    color: 0xFFEF6C00,
  ),
  KidsStory(
    title: 'Jesus Heals the Blind Man',
    emoji: '👀',
    book: 'John', chapter: 9, startVerse: 1, endVerse: 11,
    blurb: 'A man born blind sees for the very first time.',
    color: 0xFF00838F,
  ),
  KidsStory(
    title: 'Palm Sunday',
    emoji: '🌿',
    book: 'Matthew', chapter: 21, startVerse: 1, endVerse: 11,
    blurb: 'People wave palm branches and shout Hosanna!',
    color: 0xFF558B2F,
  ),
  KidsStory(
    title: 'The Last Supper',
    emoji: '🍷',
    book: 'Matthew', chapter: 26, startVerse: 17, endVerse: 30,
    blurb: 'Jesus shares a special meal with his friends.',
    color: 0xFF4E342E,
  ),
  KidsStory(
    title: 'Jesus Rises to Heaven',
    emoji: '☁️',
    book: 'Acts', chapter: 1, startVerse: 6, endVerse: 11,
    blurb: 'Jesus goes up to heaven while his friends watch.',
    color: 0xFF5C6BC0,
  ),
  KidsStory(
    title: "Peter's Big Day",
    emoji: '🔥',
    book: 'Acts', chapter: 2, startVerse: 1, endVerse: 13,
    blurb: 'The Holy Spirit comes like wind and fire.',
    color: 0xFFD32F2F,
  ),
  KidsStory(
    title: "Paul's Shipwreck",
    emoji: '⚓',
    book: 'Acts', chapter: 27, startVerse: 13, endVerse: 44,
    blurb: 'A wild storm, but everyone makes it to shore.',
    color: 0xFF37474F,
  ),
  KidsStory(
    title: 'Jesus Turns Water into Wine',
    emoji: '🍷',
    book: 'John', chapter: 2, startVerse: 1, endVerse: 11,
    blurb: 'Jesus does his very first miracle at a wedding!',
    color: 0xFF880E4F,
  ),
  KidsStory(
    title: 'The Mustard Seed',
    emoji: '🌱',
    book: 'Matthew', chapter: 13, startVerse: 31, endVerse: 32,
    blurb: 'The tiniest seed grows into the biggest tree.',
    color: 0xFF33691E,
  ),
  KidsStory(
    title: 'Jesus Blesses the Children',
    emoji: '👧',
    book: 'Mark', chapter: 10, startVerse: 13, endVerse: 16,
    blurb: "Jesus says, 'Let the little children come to me!'",
    color: 0xFFFF8F00,
  ),
  KidsStory(
    title: 'The Wise & Foolish Builders',
    emoji: '🏠',
    book: 'Matthew', chapter: 7, startVerse: 24, endVerse: 27,
    blurb: 'Build your house on the rock, not the sand!',
    color: 0xFF795548,
  ),
  KidsStory(
    title: 'Lazarus Lives Again',
    emoji: '😮',
    book: 'John', chapter: 11, startVerse: 38, endVerse: 44,
    blurb: 'Jesus calls Lazarus out of the tomb.',
    color: 0xFF4A148C,
  ),
  KidsStory(
    title: 'The Ten Lepers',
    emoji: '🙏',
    book: 'Luke', chapter: 17, startVerse: 11, endVerse: 19,
    blurb: 'Ten are healed, but only one says thank you.',
    color: 0xFF00695C,
  ),
  KidsStory(
    title: 'The Talents',
    emoji: '💰',
    book: 'Matthew', chapter: 25, startVerse: 14, endVerse: 30,
    blurb: 'Use your gifts wisely and they\'ll grow!',
    color: 0xFFFF6F00,
  ),
  KidsStory(
    title: 'Jesus Washes Feet',
    emoji: '🦶',
    book: 'John', chapter: 13, startVerse: 1, endVerse: 17,
    blurb: 'The King kneels down to serve his friends.',
    color: 0xFF1A237E,
  ),
  KidsStory(
    title: 'Road to Emmaus',
    emoji: '🚶',
    book: 'Luke', chapter: 24, startVerse: 13, endVerse: 35,
    blurb: "Two friends walk with a stranger... it's Jesus!",
    color: 0xFF827717,
  ),
  KidsStory(
    title: 'Philip & the Ethiopian',
    emoji: '📖',
    book: 'Acts', chapter: 8, startVerse: 26, endVerse: 40,
    blurb: 'Philip runs to a chariot and explains the Bible.',
    color: 0xFF006064,
  ),
];
